AddEventHandler('freezeAdjust', function()
    FreezeEntityPosition(GetPlayerPed(-1), true)
    Citizen.Wait(3500)
    FreezeEntityPosition(GetPlayerPed(-1), false)
end)

AddEventHandler('freezeAdjustExpert', function()
    FreezeEntityPosition(GetPlayerPed(-1), true)
    TriggerEvent("deadLoad")
    Citizen.Wait(8000)
    DoScreenFadeIn(4000)
    FreezeEntityPosition(GetPlayerPed(-1), false)
    TriggerEvent("chatMessage", "System ", {1,170,0}, "You're still dead , keep in mind ;D")
end)