--combat@damage@writheidle_a      writhe_idle_c
--mini@cpr@char_b@cpr_str         cpr_fail
--mini@cpr@char_a@cpr_str         cpr_pumpchest
--melee@large_wpn@streamed_core   ground_attack_on_spot
-- anim@mp_snowball pickup_snowball 2000
-- missfbi_s4mop	put_down_bucket 1300